version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3080:3080"
    environment:
      # This points Unleash to its backing database (defined in the `db` section below)
      DATABASE_URL: "postgres://postgres:hexagonal@db/db"
      DATABASE_SSL: "false"
      # Changing log levels:
      LOG_LEVEL: "warn"
    depends_on:
      db:
        condition: service_healthy
    command: ["yarn", "start"]
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3080/api/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s
  db:
    expose:
      - "5432"
    image: postgres:15
    environment:
      # create a database called `db`
      POSTGRES_DB: "db"
      # trust incoming connections blindly (DON'T DO THIS IN PRODUCTION!)
      POSTGRES_HOST_AUTH_METHOD: "trust"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=postgres",
          "--host=127.0.0.1",
          "--port=5432",
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
